# Setup
title:               Excalibur-Coupling
tagline:             ''
description:         'A Cross-Cutting Excalibur Project'
url:                 https://excalibur-coupling.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
# google_analytics_id:
github:
  repo: https://github.com/excalibur-coupling
